before:
  hooks:
    - go mod tidy
builds:
  # You can have multiple builds defined as a yaml list
  - #
    goos:
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Default: [ '386', 'amd64', 'arm64' ]
    goarch:
      - amd64
      - arm64
